"""Add operational fields to Twin and TwinHistory.

Revision ID: 3d7e9f2a1b3c
Revises: 75afe8b576fb
Create Date: 2026-09-24 18:14:00.000000
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3d7e9f2a1b3c"
down_revision = "75afe8b576fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    operational_status_enum = postgresql.ENUM(
        "HEALTHY",
        "WARNING",
        "DEGRADED",
        "CRITICAL",
        "UNKNOWN",
        "STALE",
        name="twinoperationalstatus",
        create_type=False,
    )
    operational_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "twins",
        sa.Column(
            "operational_status",
            operational_status_enum,
            nullable=False,
            server_default="UNKNOWN",
        ),
    )
    op.create_index(
        "ix_twins_operational_status",
        "twins",
        ["operational_status"],
        unique=False,
    )
    op.add_column(
        "twins",
        sa.Column("state_version", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "twins",
        sa.Column(
            "trends",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="{}",
        ),
    )
    op.add_column(
        "twins",
        sa.Column(
            "anomalies",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="{}",
        ),
    )
    op.add_column(
        "twin_history",
        sa.Column("state_version", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("twin_history", "state_version")
    op.drop_column("twins", "anomalies")
    op.drop_column("twins", "trends")
    op.drop_column("twins", "state_version")
    op.drop_index("ix_twins_operational_status", table_name="twins")
    op.drop_column("twins", "operational_status")
    # Drop the enum type
    operational_status_enum = postgresql.ENUM(
        "HEALTHY",
        "WARNING",
        "DEGRADED",
        "CRITICAL",
        "UNKNOWN",
        "STALE",
        name="twinoperationalstatus",
    )
    operational_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
